### PR TITLE
refactor(log): convert from logrus to zerolog

### PR DESCRIPTION
**Pull request by alankan886**
## Proposed change

Converting logrus to zerolog in the project, #66.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Refactor

## Checklist

- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Review by wass3r — COMMENTED** [review]
Looks great - thanks a ton for making those changes. Might consider using `zerolog.ConsoleWriter` for CLI mode at some point, but thanks for the note in the story.

One minor request - can you run `make clean` or at least `go mod tidy` and commit the changes (should just be go.sum) and we're ready to merge, i think.

**Comment by alankan886** [comment]
Hey @wass3r, just ran both `make clean` and `go mod tidy`, no changes in files.

**Comment by wass3r** [comment]
Hmm, probably user error on my part. Otherwise maybe Go version difference? I'll double check when I get on a machine. Either way, not a huge deal. Thank you!

**Comment by alankan886** [comment]
You are correct about the Go version. I upgraded from 1.15.7 to 1.16.3, ran `go mod tidy` again and some dependencies were removed in go.sum.

Thank you for going over the PR, please let me know if you need anything else from me!

**Comment by wass3r** [comment]
Awesome - thank you for the PR and follow-up! Appreciate it!

**Review by wass3r — APPROVED** [review]

**Pull request merged**
