### PR TITLE
updated docker files to use go modules

### LINKED ISSUE #103: Update Dockerfile(s) to utilize go modules

### PR DESCRIPTION
**Pull request by sarge**
## Proposed change

Updates docker files. 
closes #103 

## Types of changes

What types of changes is this pull request introducing to flottbot? _Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

You can fill this out after creating your PR. _Put an `x` in the boxes that apply_

- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by sjqnn** [comment]
If we're ripping out dep from all of the image flavored Dockerfiles, we may as well remove it from the base `Dockerfile` as well. https://github.com/target/flottbot/blob/master/docker/Dockerfile#L8

**Comment by sarge** [comment]
@sjqnn Updated that one too:)

**Comment by JordanSussman** [comment]
LGTM besides the one minor Makefile update.

**Comment by JordanSussman** [comment]
I just resolved the merge conflicts and addressed the one issue for the Makefile. Anyone else have objections to getting this merged?

**Pull request merged**
