### PR TITLE
Improvements to argument processing

### PR DESCRIPTION
**Pull request by pronovic**
## Proposed change

This PR fixes a bug in `utils.parse.FindArgs`.   `FindArgs` doesn’t properly handle the case where there is an empty quoted argument, like when a variable is empty.  

For example, our rules file might have a command like this:

```yaml
cmd: '/usr/bin/whatever "${_user.id}" "${_user.email}" "${_user.firstname}" "${_user.lastname}" "${_channel.id}" "${_channel.name}" "${_raw_user_input}"'
```

When someone interacts with the bot in a channel, the generated command looks something like this:

```sh
/usr/bin/whatever "userid" "email@domain" "First" "Last" "channelid" "channelname" "string of words"
```

However, when someone interacts with the bot in the **Apps** section of Slack, there is no channel name, so `${_channel.name}` is empty.  Under those circumstances, the generated command looks like this:

```sh
/usr/bin/whatever "userid" "email@domain" "First" "Last" "channelid" "" "string of words"
```

The current regular expression gets confused by the empty `""`.  As a result, the arguments passed to the script actually end up being:

```
"userid" "email@domain" "First" "Last" " " "string" "of" "words"
```

The modified regular expression resolves this problem by explicitly allowing empty arguments with 3 types of quotes.

The new regular expression also tightens up the match so that only pairs of the same quote character are valid.  For instance, `'whatever"` is not considered a quoted argument, since it's not valid shell syntax.   Only `'whatever'`, `"whatever"`, etc. match.  

## Types of changes

What types of changes is this pull request introducing to flottbot? _Put an `x` in the boxes that apply_

- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

You can fill this out after creating your PR. _Put an `x` in the boxes that apply_

- [X] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

I have added unit tests, and also tested manually through the CLI interface.  I also manually verified that the regular expression works through interactive testing on regex101.com.

### CODE REVIEW

**Comment by pronovic** [comment]
Hmm.  It seems like maybe the simplest solution is to have two different functions for the two different use cases.  If you want, I can rework my PR so that my new implementation is used only for the place I was having a problem.  Let me know what you want me to do.

**Comment by pa3ng** [comment]
@pronovic After discussing a bit further, we think having two different functions would be the better approach (even if the difference between the two is rather minimal). I think as long as we name the two functions appropriately for their own use cases it should be fine, e.g. `RuleArgTokenizer` and `ExecArgTokenizer`.

**Comment by pronovic** [comment]
Sure.  When I have a few minutes, I'll adjust my PR to split out my new version into a separate function.

**Comment by pronovic** [comment]
@wass3r @pa3ng I split up `FindArgs` into `RuleArgTokenizer` and `ExecArgTokenizer`.  I've tested this locally in CLI mode, and it seems to be working fine.

I also found the original unit tests for `FindArgs` (sorry, missed that originally) and wrote a set of new tests for `ExecArgTokenizer`, so I'm pretty sure the new function works as I intended.  If there are other test cases you'd like to see, let me know and I'll add them.   I can also add other tests for the original code.  Thus far, I've shied away from that, since I don't fully understand the expectations for the original code.  

If you review my recent commits, you'll find a few extra debug messages, which I found useful.  I also added `.idea` to the `.gitignore` file.  If you would prefer, I can remove any or all of these changes.

**Pull request merged**
