### PR TITLE
feat: remote for google chat

### PR DESCRIPTION
**Pull request by justmiles**
## Proposed change

Hi team! This PR adds initial support for Google Chat (#221). There's is an accompanying pull request for documentation here: https://github.com/target/flottbot-docs/pull/56

Any feedback is appreciated!

## Types of changes

What types of changes is this pull request introducing to flottbot? _Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

You can fill this out after creating your PR. _Put an `x` in the boxes that apply_

- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by wass3r** [comment]
Thanks a ton for the PR(s). Love the doc PR too. This looks great at a glance. Will do a deeper dive including set up and running this sometime this week. Thanks for taking the time!

**Comment by oCephaso** [comment]
> Thanks a ton for the PR(s). Love the doc PR too. This looks great at a glance. Will do a deeper dive including set up and running this sometime this week. Thanks for taking the time!

Has there been any progress on this PR? My company is interested in using Flottbot and remote would be good for our Google implementation

Thanks

**Comment by wass3r** [comment]
Sorry for the delay. Had a few personal things come up. I did one attempt at setting this up some time ago with the docs and didn't make it all the way. I don't think it was an issue with the docs though. Likely, user error. I will give it another shot. In the meantime, if you don't mind getting the branch up-to-date, i will pause on the other PRs until this is resolved.

**Comment by wass3r** [comment]
ah yes. i got stuck on "Google Chat API is only available to Google Workspace users" - will try and see how to get that resolved

**Review by wass3r — DISMISSED** [review]
i'm not able to test without a workspace account, but the implementation looks fine - thanks for the work.

**Comment by justmiles** [comment]
> In the meantime, if you don't mind getting the branch up-to-date, i will pause on the other PRs until this is resolved.
@wass3r - this is up to date now.

**Comment by justmiles** [comment]
Ran into an issue with unknown message types, but resolved it with 543ca20.

**Review by wass3r — APPROVED** [review]
thanks again, also for your patience 🙇🏼

**Pull request merged**
